# changes to native R support in Travis CI

os: linux
language: r
r: 3.1

sudo: required
warnings_are_errors: false
cran: http://cran.rstudio.com
cache: packages

notifications:
  email:
    on_success: change
    on_failure: change
